name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  ci:
    uses: globalprojob/.github/.github/workflows/node-ci.yml@main
    with:
      node-version: '20'
      package-manager: 'npm' # ihtiyaca göre pnpm/yarn
      install-cmd: 'ci'
      build: true
      test: true
      working-directory: '.'
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
