name: Notify Discord on Releases

on:
  release:
    types: [published]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Prepare payload for Release
        run: |
          python3 - <<'PY'
import json, os
ev = json.loads(open(os.environ['GITHUB_EVENT_PATH']).read())
rel = ev['release']
body = (rel.get('body') or '')[:800]
payload = {
  "username": "GitHub Notifier",
  "content": f"**New Release:** {rel.get('name') or rel['tag_name']} ({rel['tag_name']})\n{rel['html_url']}"
}
if body:
  payload["embeds"] = [{"title":"Release Notes","description": body,"url": rel["html_url"]}]
open('payload.json','w').write(json.dumps(payload))
PY
      - name: Send to Discord
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: |
          curl -sS -f -X POST -H "Content-Type: application/json" \
            -d @payload.json "$DISCORD_WEBHOOK_URL"
