name: Notify Discord on Pull Requests

on:
  pull_request:
    types: [opened, ready_for_review, reopened, closed]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Prepare payload for PR
        run: |
          python3 - <<'PY'
          import json, os
          ev = json.loads(open(os.environ['GITHUB_EVENT_PATH']).read())
          pr = ev['pull_request']
          action = ev['action']
          if action == 'closed' and pr.get('merged'):
              action = 'merged'
          body = (pr.get('body') or '')[:300]
          payload = {
            "username": "GitHub Notifier",
            "content": f"**PR:** {pr['title']} ({action})\nBy: {pr['user']['login']}\n{pr['html_url']}"
          }
          if body:
            payload["embeds"] = [{"title":"PR Preview","description": body,"url": pr["html_url"]}]
          open('payload.json','w').write(json.dumps(payload))
          PY

      - name: Send to Discord
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: |
          curl -sS -f -X POST -H "Content-Type: application/json" \
            -d @payload.json "$DISCORD_WEBHOOK_URL"
